const router = require('express').Router();
const ctrl = require('../controllers/orderController');
const { protect, admin } = require('../middleware/auth');
router.post('/', protect, ctrl.createOrder);
router.get('/my', protect, ctrl.getMyOrders);
router.get('/all', protect, admin, ctrl.getAllOrders);
router.get('/:id', protect, ctrl.getOrder);
router.put('/:id/pay', protect, ctrl.payOrder);
router.put('/:id/status', protect, admin, ctrl.updateOrderStatus);
module.exports = router;
