const router = require('express').Router();
const ctrl = require('../controllers/productController');
const { protect, admin } = require('../middleware/auth');
router.get('/', ctrl.getProducts);
router.get('/featured-all', ctrl.getFeaturedProducts);
router.get('/:id', ctrl.getProduct);
router.post('/', protect, admin, ctrl.createProduct);
router.put('/:id', protect, admin, ctrl.updateProduct);
router.delete('/:id', protect, admin, ctrl.deleteProduct);
router.post('/:id/reviews', protect, ctrl.addReview);
module.exports = router;
